### ISSUE TITLE
Failed to load after last FactorioExtended-Plus-Power update to 1.0.2

### ISSUE THREAD

**Issue by Bavarian** [SirJMO/FactorioExtended-Plus-CompoundSolars#1]
15.559 Mods to disable:Failed to load mods: Error while running setup for entity prototype "solar-panel" (solar-panel): next_upgrade target (solar-panel-mk2) must have the same fast_replaceable_group ( != solar-panel).

Mods to be disabled:
• FactorioExtended-Plus-Power (1.0.2)
• FactorioExtended-Plus-CompoundSolars (0.1.3)
• FactorioExtended-Plus-Power (1.0.2)

Failure only shows up when FactorioExtended-Plus-CompoundSolars is enabled

**Comment by vakus** [comment]
This bug is to do with FactorioExtended-Plus-Power, see https://github.com/jimmyjon711/FactorioExtended-Plus-Power/issues/27
